package io.github.mohammadhadimohammadi2007_dot.lobby.server.compat;

import net.minestom.server.entity.EntityType;
import net.minestom.server.item.Material;
import org.junit.jupiter.api.Test;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Checks the generated 1.8 lists.
 *
 * <p>The item list is rebuilt here from {@code 1-8-source.json}, which holds the slice of upstream data
 * the generator used: the item ids and metadata values Minecraft 1.8 had (from minecraft-data) and the
 * modern name each of them maps to (from ViaVersion's mapping files). If someone edits the resource by
 * hand, or the generator changes what it writes, this test fails. That matters because a hand-written
 * list silently contained a dozen items that 1.8 never had.
 */
class LegacyItemsTest {

    private static JsonObject sourceData() throws Exception {
        try (InputStream in = LegacyItemsTest.class.getResourceAsStream("/compat/1-8-source.json")) {
            assertNotNull(in, "the committed source data is missing");
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                return JsonParser.parseReader(reader).getAsJsonObject();
            }
        }
    }

    @Test
    void itemListMatchesTheUpstreamSourceData() throws Exception {
        JsonObject source = sourceData();
        JsonObject names = source.getAsJsonObject("legacyToModernName");
        JsonObject renames = source.getAsJsonObject("renamedAfter1_13");
        Set<String> withoutModernItem = new LinkedHashSet<>();
        source.getAsJsonArray("noModernItem").forEach(name -> withoutModernItem.add(name.getAsString()));

        Set<String> expected = new LinkedHashSet<>();
        for (var entry : source.getAsJsonArray("itemIdsAndMetadata")) {
            JsonArray pair = entry.getAsJsonArray();
            int id = pair.get(0).getAsInt();
            int metadata = pair.get(1).getAsInt();
            // 1.12 and older packed an item's id and metadata into one number.
            var mapped = names.get(String.valueOf(id * 16 + metadata));
            assertNotNull(mapped, "no mapping for " + id + ":" + metadata);
            String name = mapped.getAsString();
            if (renames.has(name)) {
                name = renames.get(name).getAsString();
            }
            if (!withoutModernItem.contains(name)) {
                expected.add(name);
            }
        }

        Set<String> generated = LegacyItems.materials();
        assertEquals(new TreeSet<>(expected), new TreeSet<>(generated),
                "the generated item list no longer matches the source data."
                        + " Run: python tools/generate-1-8-list.py");
        assertTrue(generated.size() > 500, "suspiciously few items: " + generated.size());
        // Every name the generator left out must really have no item today, so nothing hides behind it.
        for (String name : withoutModernItem) {
            assertNull(Material.fromKey("minecraft:" + name), name + " does have an item, so it belongs in the list");
        }
    }

    /** Catches renames: every generated name must still exist in the Minecraft version we run. */
    @Test
    void everyGeneratedNameExistsToday() {
        assertEquals(List.of(), LegacyItems.unknownNames());
    }

    @Test
    void resourcesSayTheyAreGenerated() throws Exception {
        for (String file : List.of("/compat/minecraft-1-8-materials.txt", "/compat/minecraft-1-8-entities.txt")) {
            try (InputStream in = LegacyItemsTest.class.getResourceAsStream(file)) {
                assertNotNull(in, file);
                String firstLine = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8)).readLine();
                assertTrue(firstLine.contains("Generated by tools/generate-1-8-list.py"), file + ": " + firstLine);
            }
        }
    }

    @Test
    void knowsWhatIsOldAndWhatIsNew() {
        assertTrue(LegacyItems.exists(Material.CHEST));
        assertTrue(LegacyItems.exists(Material.DIAMOND_SWORD));
        assertTrue(LegacyItems.exists(Material.LIGHT_BLUE_STAINED_GLASS_PANE));
        assertTrue(LegacyItems.exists(Material.PLAYER_HEAD));
        assertTrue(LegacyItems.exists(Material.CREEPER_SPAWN_EGG));
        assertTrue(LegacyItems.exists(Material.LAPIS_LAZULI));
        // Added after 1.8: shulker boxes (1.11), concrete (1.12), barrels (1.14), copper (1.17),
        // elytra (1.9), beds per colour (1.12), and the 1.19.4 display entities' spawn eggs.
        assertFalse(LegacyItems.exists(Material.WHITE_SHULKER_BOX));
        assertFalse(LegacyItems.exists(Material.LIME_CONCRETE));
        assertFalse(LegacyItems.exists(Material.BARREL));
        assertFalse(LegacyItems.exists(Material.COPPER_INGOT));
        assertFalse(LegacyItems.exists(Material.ELYTRA));
        assertFalse(LegacyItems.exists(Material.SHULKER_SPAWN_EGG));
    }

    @Test
    void knowsOldAndNewEntityTypes() {
        assertTrue(LegacyItems.exists(EntityType.ZOMBIE));
        assertTrue(LegacyItems.exists(EntityType.ARMOR_STAND));
        assertTrue(LegacyItems.exists(EntityType.VILLAGER));
        assertTrue(LegacyItems.exists(EntityType.ZOMBIFIED_PIGLIN), "renamed from PigZombie");
        assertTrue(LegacyItems.exists(EntityType.MAGMA_CUBE), "renamed from LavaSlime");
        assertTrue(LegacyItems.exists(EntityType.SNOW_GOLEM), "renamed from SnowMan");
        assertTrue(LegacyItems.exists(EntityType.END_CRYSTAL), "renamed from EnderCrystal");
        // Added after 1.8: shulker (1.11), warden (1.19), display entities (1.19.4).
        assertFalse(LegacyItems.exists(EntityType.SHULKER));
        assertFalse(LegacyItems.exists(EntityType.WARDEN));
        assertFalse(LegacyItems.exists(EntityType.TEXT_DISPLAY));
        assertFalse(LegacyItems.exists(EntityType.INTERACTION));
        assertEquals(57, LegacyItems.entityTypes().size());
    }
}
