package io.github.mohammadhadimohammadi2007_dot.lobby.server.compat;

import net.minestom.server.entity.EntityType;
import net.minestom.server.item.Material;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Warns about materials and entity types that do not exist in Minecraft 1.8.
 *
 * <p>Players on old clients reach the lobby through ViaRewind, which has to replace anything their client
 * does not know, so a menu item or NPC may look different to them than intended. Everything still works,
 * so this only logs a warning once per option, with the config option named.
 *
 * <p>Both lists are generated by {@code tools/generate-1-8-list.py} from PrismarineJS/minecraft-data:
 * which ids 1.8 had, and which modern name each old "id:metadata" became. Do not edit them by hand:
 * {@code LegacyItemsTest} checks the item list against the same source data.
 */
public final class LegacyItems {

    private static final Logger LOGGER = LoggerFactory.getLogger(LegacyItems.class);
    private static final String MATERIALS_FILE = "/compat/minecraft-1-8-materials.txt";
    private static final String ENTITIES_FILE = "/compat/minecraft-1-8-entities.txt";

    private static final Set<String> MATERIALS = load(MATERIALS_FILE);
    private static final Set<String> ENTITY_TYPES = load(ENTITIES_FILE);
    /** Options already warned about, so a reload does not repeat every warning. */
    private static final Set<String> WARNED = new HashSet<>();

    private LegacyItems() {
    }

    /** True if this material exists in Minecraft 1.8. */
    public static boolean exists(Material material) {
        return MATERIALS.contains(name(material.key().value()));
    }

    /** True if this entity type exists in Minecraft 1.8. */
    public static boolean exists(EntityType type) {
        return ENTITY_TYPES.contains(name(type.key().value()));
    }

    /**
     * Logs a warning (once per option) if {@code material} is unknown to 1.8 clients.
     *
     * @param option where it was set, e.g. {@code menus.yml: servers.items.bedwars.material}
     */
    public static void warnIfMissing(Material material, String option) {
        if (!exists(material)) {
            warn(option, material.key().value(), "item");
        }
    }

    /** Logs a warning (once per option) if {@code type} is unknown to 1.8 clients. */
    public static void warnIfMissing(EntityType type, String option) {
        if (!exists(type)) {
            warn(option, type.key().value(), "entity");
        }
    }

    /** Forgets which options were warned about, so a reload reports current problems again. */
    public static synchronized void resetWarnings() {
        WARNED.clear();
    }

    private static synchronized void warn(String option, String value, String kind) {
        if (!WARNED.add(option + "=" + value)) {
            return;
        }
        LOGGER.warn("{}: the {} '{}' does not exist in Minecraft 1.8, so players on old clients"
                + " (through ViaRewind) are shown a replacement. It still works for everyone else.",
                option, kind, value);
    }

    private static String name(String key) {
        return key.toLowerCase(Locale.ROOT);
    }

    private static Set<String> load(String file) {
        Set<String> names = new LinkedHashSet<>();
        try (InputStream in = LegacyItems.class.getResourceAsStream(file)) {
            if (in == null) {
                LOGGER.warn("{} is missing from the jar, so 1.8 compatibility warnings are off", file);
                return Set.of();
            }
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String trimmed = line.strip();
                    if (!trimmed.isEmpty() && !trimmed.startsWith("#")) {
                        names.add(name(trimmed));
                    }
                }
            }
        } catch (IOException e) {
            LOGGER.warn("Could not read {}, so 1.8 compatibility warnings are off: {}", file, e.getMessage());
            return Set.of();
        }
        return Set.copyOf(names);
    }

    /** The generated item names, for the test. */
    static Set<String> materials() {
        return MATERIALS;
    }

    /** The generated entity type names, for the test. */
    static Set<String> entityTypes() {
        return ENTITY_TYPES;
    }

    /** Names in the bundled lists that no longer exist in this Minecraft version. For the test only. */
    static List<String> unknownNames() {
        Set<String> knownMaterials = new HashSet<>();
        for (Material material : Material.values()) {
            knownMaterials.add(name(material.key().value()));
        }
        Set<String> knownEntities = new HashSet<>();
        for (EntityType type : EntityType.values()) {
            knownEntities.add(name(type.key().value()));
        }
        List<String> unknown = new ArrayList<>();
        MATERIALS.stream().filter(entry -> !knownMaterials.contains(entry)).forEach(unknown::add);
        ENTITY_TYPES.stream().filter(entry -> !knownEntities.contains(entry)).forEach(unknown::add);
        return unknown;
    }
}
