#!/usr/bin/env python3
"""Generates the lists of items and entity types that exist in Minecraft 1.8.

The lobby warns server owners when a config names something old clients cannot show (see
LegacyItems.java). Writing that list by hand went wrong, so it is generated from real data. Every
source is PrismarineJS/minecraft-data, which is MIT licensed like this project:

  * pc/1.8 items.json says which item ids and metadata values 1.8 had, and entities.json which entity
    types.
  * pc/common/legacy.json turns a legacy "id:metadata" into the flattened 1.13 name, for example
    "160:3" into minecraft:light_blue_stained_glass_pane. Its "items" table is tried first and its
    "blocks" table second, for the few 1.8 items that only appear as a block (such as "44:2",
    petrified_oak_slab).
  * minecraft-data for the version the lobby runs (MODERN_VERSION) says which of those names still
    exist. Anything that does not is left out: a config cannot name it anyway.

Two things legacy.json cannot answer: 1.8 had one spawn egg whose metadata was the entity id, which
1.13 split per mob, and a few items were renamed again after 1.13. The spawn eggs are resolved through
the 1.8 entity ids, and the renames are the two tables below. Those tables go into the test fixture as
well, so the Java test can rebuild the list without trusting this script.

Usage (from the repository root):

    python tools/generate-1-8-list.py                 # downloads the sources and writes the lists
    python tools/generate-1-8-list.py --cache-dir d   # keeps/reuses the downloads in d (offline runs)
"""

import argparse
import json
import pathlib
import sys
import urllib.request

# The Minecraft version the lobby runs on; only names that still exist there are kept.
MODERN_VERSION = "26.1"

MINECRAFT_DATA = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/"

SOURCES = {
    "items-1.8.json": MINECRAFT_DATA + "1.8/items.json",
    "entities-1.8.json": MINECRAFT_DATA + "1.8/entities.json",
    "legacy.json": MINECRAFT_DATA + "common/legacy.json",
    "items-modern.json": MINECRAFT_DATA + MODERN_VERSION + "/items.json",
    "entities-modern.json": MINECRAFT_DATA + MODERN_VERSION + "/entities.json",
}

# Items the flattening named one thing in 1.13 and something else later on.
RENAMED_ITEMS = {
    "sign": "oak_sign",
    "grass": "short_grass",
    "rose_red": "red_dye",
    "cactus_green": "green_dye",
    "dandelion_yellow": "yellow_dye",
}

# 1.8 internal entity names (minecraft-data) to the names Minecraft uses today. Only renames belong
# here, never additions. "None" means it is not a real entity type, just a grouping in the 1.8 data.
RENAMED_ENTITIES = {
    "Mob": None,
    "Monster": None,
    "PigZombie": "zombified_piglin",
    "LavaSlime": "magma_cube",
    "WitherBoss": "wither",
    "MushroomCow": "mooshroom",
    "SnowMan": "snow_golem",
    "Ozelot": "ocelot",
    "VillagerGolem": "iron_golem",
    "EntityHorse": "horse",
    "PrimedTnt": "tnt",
    "FallingSand": "falling_block",
    "ThrownEgg": "egg",
    "ThrownEnderpearl": "ender_pearl",
    "ThrownPotion": "splash_potion",
    "ThrownExpBottle": "experience_bottle",
    "EyeOfEnderSignal": "eye_of_ender",
    "FireworksRocketEntity": "firework_rocket",
    "LeashKnot": "leash_knot",
    "MinecartRideable": "minecart",
    "EnderCrystal": "end_crystal",
    "Boat": "oak_boat",
    "Fishing Float": "fishing_bobber",
    "Item": "item",
}

# Entities every version has, which the 1.8 data file leaves out (it lists only mobs and objects).
ALWAYS_PRESENT_ENTITIES = ["player", "experience_orb", "painting", "lightning_bolt"]

HEADER = """# Generated by tools/generate-1-8-list.py - do not edit by hand.
#
# {what} that exist in Minecraft 1.8, by the name Minecraft uses today.
#
# Used only to warn server owners: anything NOT in this list still works, but players on 1.8 reach the
# lobby through ViaRewind, which has to show them a replacement, so it may look wrong to them.
#
# Source: PrismarineJS/minecraft-data (pc/1.8, pc/common/legacy.json and pc/{modern}), MIT licensed.
#
# {count} entries.
"""


def fetch(name, url, cache_dir):
    """Reads a source file, from the cache if it is there, otherwise over the network."""
    if cache_dir is not None:
        cached = cache_dir / name
        if cached.is_file():
            return json.loads(cached.read_text(encoding="utf-8"))
    print("downloading " + url, file=sys.stderr)
    with urllib.request.urlopen(url, timeout=60) as response:
        raw = response.read().decode("utf-8")
    if cache_dir is not None:
        cache_dir.mkdir(parents=True, exist_ok=True)
        (cache_dir / name).write_text(raw, encoding="utf-8")
    return json.loads(raw)


def flattened_name(legacy, key):
    """The 1.13 name legacy.json gives for an "id:metadata" key, without namespace or block state."""
    name = legacy["items"].get(key) or legacy["blocks"].get(key)
    if name is None:
        return None
    # The blocks table names a block state, such as "minecraft:oak_log[axis=x]".
    return name.removeprefix("minecraft:").split("[")[0]


def legacy_pairs(items_1_8, legacy, entities_1_8):
    """Every (id, metadata) 1.8 had that can be named today, with that name."""
    by_entity_id = {entity.get("internalId"): modern_entity_name(entity["name"])
                    for entity in entities_1_8}
    pairs = []
    names = {}
    skipped = []
    for item in items_1_8:
        variations = item.get("variations") or [{"metadata": 0}]
        for variation in variations:
            metadata = variation["metadata"]
            # 1.12 and older named an item by its id plus a metadata value.
            key = str(item["id"]) + ":" + str(metadata)
            name = flattened_name(legacy, key)
            if name is None and item["name"] == "spawn_egg":
                # 1.8 had one spawn egg whose metadata was the entity id; 1.13 split it per mob.
                entity = by_entity_id.get(metadata)
                name = None if entity is None else entity + "_spawn_egg"
            if name is None:
                skipped.append(item["name"] + ":" + str(metadata))
                continue
            pairs.append([item["id"], metadata])
            names[key] = name
    return pairs, names, skipped


def item_names(pairs, names, modern_items):
    """The modern item names of those pairs, and the ones that have no modern item."""
    kept = []
    dropped = []
    seen = set()
    for item_id, metadata in pairs:
        name = names[str(item_id) + ":" + str(metadata)]
        name = RENAMED_ITEMS.get(name, name)
        if name in seen:
            continue
        seen.add(name)
        if name in modern_items:
            kept.append(name)
        else:
            dropped.append(name)
    return kept, dropped


def entity_names(entities_1_8, modern_entities):
    """Every 1.8 entity type by today's name, and the ones that have no modern type."""
    kept = []
    dropped = []
    seen = set()
    candidates = [modern_entity_name(entity["name"]) for entity in entities_1_8]
    candidates += ALWAYS_PRESENT_ENTITIES
    for name in candidates:
        if name is None or name in seen:
            continue
        seen.add(name)
        if name in modern_entities:
            kept.append(name)
        else:
            dropped.append(name)
    return kept, dropped


def modern_entity_name(old):
    """Today's name for a 1.8 internal entity name, or None if it is not a real type."""
    if old in RENAMED_ENTITIES:
        return RENAMED_ENTITIES[old]
    return snake_case(old)


def snake_case(name):
    """Turns "CaveSpider" into "cave_spider"."""
    out = []
    for index, character in enumerate(name):
        if character.isupper() and index > 0 and not name[index - 1].isupper():
            out.append("_")
        out.append(character.lower())
    return "".join(out)


def write_list(path, what, names):
    path.parent.mkdir(parents=True, exist_ok=True)
    body = HEADER.format(what=what, count=len(names), modern=MODERN_VERSION)
    path.write_text(body + "\n" + "\n".join(sorted(names)) + "\n", encoding="utf-8")
    print("wrote " + str(len(names)) + " " + what.lower() + " to " + str(path))


def write_fixture(path, pairs, names, dropped_items):
    """
    Writes what the item list was built from, so the test can rebuild it offline without trusting this
    script: the upstream pairs and names, plus the two decisions made here.
    """
    fixture = {
        "comment": "Generated by tools/generate-1-8-list.py. Do not edit by hand. legacyToModernName"
                   " comes from minecraft-data's pc/common/legacy.json, except spawn eggs, which 1.13"
                   " split per mob and which are resolved through the 1.8 entity ids.",
        "sources": SOURCES,
        "itemIdsAndMetadata": pairs,
        "legacyToModernName": names,
        "renamedAfter1_13": RENAMED_ITEMS,
        "noModernItem": sorted(dropped_items),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(fixture, indent=1) + "\n", encoding="utf-8")
    print("wrote " + str(len(pairs)) + " source pairs to " + str(path))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache-dir", type=pathlib.Path, default=None,
                        help="directory to keep the downloaded sources in, so later runs work offline")
    parser.add_argument("--out-dir", type=pathlib.Path,
                        default=pathlib.Path("lobby-server/src/main/resources/compat"),
                        help="where to write the generated lists")
    parser.add_argument("--fixture", type=pathlib.Path,
                        default=pathlib.Path("lobby-server/src/test/resources/compat/1-8-source.json"),
                        help="where to write the upstream data the test checks the item list against")
    arguments = parser.parse_args()

    sources = {name: fetch(name, url, arguments.cache_dir) for name, url in SOURCES.items()}
    modern_items = {item["name"] for item in sources["items-modern.json"]}
    modern_entities = {entity["name"] for entity in sources["entities-modern.json"]}

    pairs, names, skipped = legacy_pairs(sources["items-1.8.json"], sources["legacy.json"],
                                         sources["entities-1.8.json"])
    items, dropped_items = item_names(pairs, names, modern_items)
    entities, dropped_entities = entity_names(sources["entities-1.8.json"], modern_entities)

    if skipped:
        print("note: " + str(len(skipped)) + " 1.8 item variants have no entry in legacy.json (block"
              + " states and unused values): " + ", ".join(skipped[:6])
              + ("..." if len(skipped) > 6 else ""), file=sys.stderr)
    if dropped_items:
        print("note: " + str(len(dropped_items)) + " 1.8 items have no item in " + MODERN_VERSION
              + " and were left out: " + ", ".join(sorted(dropped_items)[:6])
              + ("..." if len(dropped_items) > 6 else ""), file=sys.stderr)
    if dropped_entities:
        print("note: " + str(len(dropped_entities)) + " 1.8 entity types have no type in "
              + MODERN_VERSION + " and were left out: " + ", ".join(sorted(dropped_entities)),
              file=sys.stderr)

    write_list(arguments.out_dir / "minecraft-1-8-materials.txt", "Items", items)
    write_list(arguments.out_dir / "minecraft-1-8-entities.txt", "Entity types", entities)
    write_fixture(arguments.fixture, pairs, names, dropped_items)
    return 0


if __name__ == "__main__":
    sys.exit(main())
